name: 'defined-networking-connect'
description: 'Connect to a Defined Networking network'
branding:
  icon: bar-chart
  color: blue
inputs:
  enrollment-code:
    description: 'defined networking enrollment code'
    required: true
  dnclient-version:
    description: 'version of dnclient to use'
    required: false
    default: cce733c1/v0.0.8
runs:
  using: "composite"
  steps: 
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: ./setup.sh
      env:
        CODE: ${{ inputs.enrollment-code }}

